---
- name: Créer deux VM
  hosts: localhost
  gather_facts: no
  vars_files:
    - myvault.yaml
  tasks:
    - name: Elasticsearch
      community.vmware.vmware_guest:
        hostname: "{{esxi_hostname}}"
        username: "{{esxi_username}}"
        password: "{{esxi_password}}"
        validate_certs: no
        folder: "/vm"
        name: OpenSearch_soc
        state: poweredon
        guest_id: centos64Guest
        disk:
          - size_gb: 50
            type: thin
            datastore: "VMFS1"
        hardware:
          memory_mb: 6144
          num_cpus: 3
          scsi: paravirtual
        networks:
          - name: VM Network
            device_type: vmxnet3
        cdrom:
          type: iso
          iso_path: "[VMFS1] ISO/debian-11.3.0-amd64-netinst(1).iso"

    - name: logstash
      community.vmware.vmware_guest:
        hostname: "{{esxi_hostname}}"
        username: "{{esxi_username}}"
        password: "{{esxi_password}}"
        validate_certs: no
        folder: "/vm"
        name: Logstash_soc
        state: poweredon
        guest_id: centos64Guest
        disk:
          - size_gb: 30
            type: thin
            datastore: "VMFS1"
        hardware:
          memory_mb: 2048
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: VM Network
            device_type: vmxnet3
        cdrom:
          type: iso
          iso_path: "[VMFS1] ISO/debian-11.3.0-amd64-netinst(1).iso"

    - name: Grafana
      community.vmware.vmware_guest:
        hostname: "{{esxi_hostname}}"
        username: "{{esxi_username}}"
        password: "{{esxi_password}}"
        validate_certs: no
        folder: "/vm"
        name: Grafana_soc
        state: poweredon
        guest_id: centos64Guest
        disk:
          - size_gb: 10
            type: thin
            datastore: "VMFS1"
        hardware:
          memory_mb: 2048
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: VM Network
            device_type: vmxnet3
        cdrom:
          type: iso
          iso_path: "[VMFS1] ISO/debian-11.3.0-amd64-netinst(1).iso"

    - name: Client1_soc
      community.vmware.vmware_guest:
        hostname: "{{esxi_hostname}}"
        username: "{{esxi_username}}"
        password: "{{esxi_password}}"
        validate_certs: no
        folder: "/vm"
        name: Client1_soc
        state: poweredon
        guest_id: centos64Guest
        disk:
          - size_gb: 10
            type: thin
            datastore: "VMFS1"
        hardware:
          memory_mb: 2048
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: VM Network
            device_type: vmxnet3
        cdrom:
          type: iso
          iso_path: "[VMFS1] ISO/debian-11.3.0-amd64-netinst(1).iso"

    - name: Client2_soc
      community.vmware.vmware_guest:
        hostname: "{{esxi_hostname}}"
        username: "{{esxi_username}}"
        password: "{{esxi_password}}"
        validate_certs: no
        folder: "/vm"
        name: Client2_soc
        state: poweredon
        guest_id: centos64Guest
        disk:
          - size_gb: 40
            type: thin
            datastore: "VMFS1"
        hardware:
          memory_mb: 4096
          num_cpus: 3
          scsi: paravirtual
        networks:
          - name: VM Network
            device_type: vmxnet3
        cdrom:
          type: iso
          iso_path: "[VMFS1] ISO/SW_DVD9_Win_Server_STD_CORE_2019_1809.18_64Bit_English_DC_STD_MLF_X22-74330.ISO"