---
- name: Créer des VMs sur ESXi sans installation automatisée
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - /home/semaphore/myvault.yaml
  tasks:
    - name: Créer la VM OpenSearch
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        folder: "/vm"
        name: OpenSearch_soc
        state: poweredon
        guest_id: "otherLinux64Guest"
        disk:
          - size_gb: 50
            type: thin
            datastore: "VMFS1"
        hardware:
          memory_mb: 6144
          num_cpus: 3
          scsi: paravirtual
        networks:
          - name: VM Network
            device_type: vmxnet3
        cdrom:
          type: iso
          iso_path: "[VMFS1] ISO/debian-11.3.0-amd64-netinst.iso"

    - name: Créer la VM Logstash
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        folder: "/vm"
        name: Logstash_soc
        state: poweredon
        guest_id: "otherLinux64Guest"
        disk:
          - size_gb: 30
            type: thin
            datastore: "VMFS1"
        hardware:
          memory_mb: 2048
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: VM Network
            device_type: vmxnet3
        cdrom:
          type: iso
          iso_path: "[VMFS1] ISO/debian-11.3.0-amd64-netinst.iso"

    - name: Créer la VM Grafana
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        folder: "/vm"
        name: Grafana_soc
        state: poweredon
        guest_id: "otherLinux64Guest"
        disk:
          - size_gb: 10
            type: thin
            datastore: "VMFS1"
        hardware:
          memory_mb: 2048
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: VM Network
            device_type: vmxnet3
        cdrom:
          type: iso
          iso_path: "[VMFS1] ISO/debian-11.3.0-amd64-netinst.iso"

    - name: Créer la VM Client1
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        folder: "/vm"
        name: Client1_soc
        state: poweredon
        guest_id: "otherLinux64Guest"
        disk:
          - size_gb: 10
            type: thin
            datastore: "VMFS1"
        hardware:
          memory_mb: 2048
          num_cpus: 2
          scsi: paravirtual
        networks:
          - name: VM Network
            device_type: vmxnet3
        cdrom:
          type: iso
          iso_path: "[VMFS1] ISO/debian-11.3.0-amd64-netinst.iso"

    - name: Créer la VM Client2
      community.vmware.vmware_guest:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: no
        folder: "/vm"
        name: Client2_soc
        state: poweredon
        guest_id: "otherLinux64Guest"
        disk:
          - size_gb: 40
            type: thin
            datastore: "VMFS1"
        hardware:
          memory_mb: 4096
          num_cpus: 3
          scsi: paravirtual
        networks:
          - name: VM Network
            device_type: vmxnet3
        cdrom:
          type: iso
          iso_path: "[VMFS1] ISO/debian-11.3.0-amd64-netinst.iso"
